using E_LearnAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_LearnAPI.DTOs
{
    public class ResultDTO
    {
        /// <summary>
        /// Primary Key - Autogenerated by database.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// This is the person's ESR Employee number.
        /// </summary>
        public int PersonId { get; set; }

        public string PersonName { get; set; }
        /// <summary>
        /// This the the ID field from the Courses table.
        /// </summary>
        public int? CourseId { get; set; }

        public string CourseDesc { get; set; }

        public string ModuleName { get; set; }

        /// <summary>
        /// This is when the result was recieved by the API.
        /// </summary>
        public DateTime CompletionDate { get; set; }
        /// <summary>
        /// This is when the result was recieved by the API.
        /// </summary>
        public DateTime Received { get; set; }
        /// <summary>
        /// This is the AD Account that sent the result message.
        /// Will only be populated when message does not come from cross origin location.
        /// </summary>
        public string FromADAcc { get; set; }
        /// <summary>
        /// Will represent if the result has been matched to a requirement and the requirement 
        /// updated based on the result.
        /// </summary>
        public bool Processed { get; set; }
        /// <summary>
        /// If application is unable to process result, an explanation will be put into this field.
        /// May be updated manually by admin staff.
        /// </summary>
        public string Comments { get; set; }


        public ResultDTO(ESRModules eSR)
        {
            this.Id = eSR.ID;
            this.PersonId = eSR.Employee;
            if (eSR.StaffID != null)
            {
                this.PersonName = eSR.Staff.Fname + " " + eSR.Staff.Sname;
            }
            this.CourseId = eSR.CourseID;   
            if (eSR.CourseID != null)
            {
                this.CourseDesc = eSR.Course.CourseName;
            }
            this.ModuleName = eSR.ModuleName;
            this.CompletionDate = eSR.CompletionDate;
            this.FromADAcc = "ESR Extract";
            this.Processed = eSR.Processed;
            this.Comments = eSR.Comments;
        }
    }

}