using E_LearnAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_LearnAPI.DTOs
{
    /// <summary>
    /// The data relating to an individual e-Learning Result.
    /// </summary>
    public class ResultDTO
    {
        /// <summary>
        /// Primary Key (Autogenerated by database).
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// This is the person's ESR Employee number.
        /// </summary>
        public int PersonId { get; set; }
        /// <summary>
        /// This is the person's username from the LMS.
        /// It should match their e-mail address.
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// The name of the person, from the training database.
        /// </summary>
        public string PersonName { get; set; }
        /// <summary>
        /// This the the ID field from the Courses table.
        /// </summary>
        public int? CourseId { get; set; }
        /// <summary>
        /// The course name of the matching course in the training database.
        /// </summary>
        public string CourseDesc { get; set; }
        /// <summary>
        /// The name of the course/module from the LMS.
        /// </summary>
        public string ModuleName { get; set; }
        /// <summary>
        /// This is the date the person completed this course/module.
        /// </summary>
        public DateTime CompletionDate { get; set; }
        /// <summary>
        /// This is when the result was recieved by the API.
        /// </summary>
        public DateTime Received { get; set; }
        /// <summary>
        /// The source of the e-Learning result.
        /// May be an AD Account or a description of where the data was provided from.
        /// </summary>
        public string FromADAcc { get; set; }
        /// <summary>
        /// Will represent if the result has been matched to a requirement and the requirement 
        /// updated based on the result.
        /// </summary>
        public bool Processed { get; set; }
        /// <summary>
        /// If application is unable to process result, an explanation will be put into this field.
        /// May be updated manually by admin staff.
        /// </summary>
        public string Comments { get; set; }

        /// <summary>
        /// Constructor - will generate a ResultDTO object from a database record.
        /// </summary>
        /// <param name="eSR">A database record of the e-Learning result.</param>
        public ResultDTO(ESRModules eSR)
        {
            this.Id = eSR.ID;
            this.PersonId = eSR.Employee;
            this.UserName = eSR.UserName;
            if (eSR.StaffID != null)
            {
                this.PersonName = eSR.Staff.Fname + " " + eSR.Staff.Sname;
            }
            this.CourseId = eSR.CourseID;   
            if (eSR.CourseID != null)
            {
                this.CourseDesc = eSR.Course.CourseName;
            }
            this.ModuleName = eSR.ModuleName;
            this.CompletionDate = eSR.CompletionDate;
            this.FromADAcc = eSR.Source;
            this.Received = eSR.Received;
            this.Processed = eSR.Processed;
            this.Comments = eSR.Comments;
        }
    }

}