// <auto-generated />
namespace E_LearnAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddESRIDtoPersonRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddESRIDtoPersonRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041506587_Add ESRID to Person Record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
