// <auto-generated />
namespace E_LearnAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class apparently_needs_another_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(apparently_needs_another_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202101191655001_apparently_needs_another_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
